### ISSUE TITLE
Link broken for pre-trained LJ model

### ISSUE THREAD

**Issue by sjkoelle** [JoungheeKim/Non-Attentive-Tacotron#1]
I was wondering if you have a working link for the pre-trained LJ model?  Thanks!

**Comment by JoungheeKim** [comment]
I re-upload the LJ model with the link
https://drive.google.com/file/d/1kwMt0YYI3vmZFgrnH7NoAKYNwPl_AYoW/view?usp=sharing

I believe that the model is not completely trained enough.
So you might can hear some robotic noise from a generated audio.

Sorry for the inconvenience.

**Comment by sjkoelle** [comment]
No problem.  Thanks!
